### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by dchmelik** [dungeons-of-moria/umoria#11]
Didn't see where to email umoria.org, but a page title has typo: [A His**ot**ry of Moria - A Classic Roguelike](https://umoria.org/history/).

Also, I thought I commented on your project before (asking if it was official) but can't find that post now, but it's good to see some bugs fixed.  I wonder if the official maintainer will let you take over, or if there will be separate C (outdated) and C++ (bugfixed) versions.  Since maybe 1993, (U)Moria has been my favourite videogame that you play a person, maybe my top favourite of all, or it shares the place with Tetris.  So, I might make a SlackBuild (so people can build an unofficial package for Slackware) for your version, but already do one for the official version, and it'd only work to have one one or the other installed to run, but that'd be okay.

**Comment by mrcook** [comment]
Thanks David, the typo is now fixed!

No, this is not an official version of Umoria, I just took it upon myself to do some long overdue maintenance :)

With my initial updates I kept to plain C code but eventually decided to move toward C++ as it seems this provides much better opportunities for safer code. At least this is the way it seems to my inexperienced C++ eyes.

Another of my goals was for this repository to also be an historical record of all the Umoria releases. So you can still go back to the last official release (https://github.com/dungeons-of-moria/umoria/tree/v5.6.0) or even one of the earlier versions (they're all tagged). So far I've managed to collect nine different releases, including the original first public release (https://github.com/dungeons-of-moria/umoria/tree/v4.8.5).

If you manage to get it compiling on Slackware please do let me know what was required and I'll update the repo here. The main thing to note is that I'm installing to the `home` directory rather than the something like `/usr/games`.
