### ISSUE TITLE
Mana lost when canceling mage spells

### ISSUE THREAD

**Issue by supersnail12345** [dungeons-of-moria/umoria#32]
The mana cost of a spell is still deducted when canceling a mage spell with the escape key. This is not the case with priest spells, which do not appear to subtract their cost upon canceling. 

Tested on Umoria 5.7.12 and 5.7.10, Windows 32 bit build. Can be duplicated by using wizard mode and casting a spell (I tested confusion, fire bolt, frost ball, and a few others.), then hitting escape when prompted for a direction.

Haven't checked the other classes that use mage spells, but this issue presumably affects them as well.

**Comment by supersnail12345** [comment]
From what I can tell, line 262 of mage_spells.cpp is to blame. It subtracts the mana regardless of whether a valid direction was picked for the spell. Haven't looked into why priests don't seem to have this problem though.

On a slightly more serious note, after some more testing I noticed that this can potentially get a character killed if selecting 'y' when casting with not enough mana, and then hitting escape to cancel the spell. What instead happens is the player is paralyzed, and have no spell to show for their hard work. 

This bug also only affects spells that require a directional input.

**Comment by mrcook** [comment]
Hi @supersnail12345, thanks again for the bug hunting!

This was again sloppy work on my part. It was a similar issue to the pray bug, although this time the _free turn_ check was missing completely :/

It's a little disturbing that happened so also had a look over the other magic commands (e.g. staffs, wands, scrolls, and quaffing) but was not able to see anything obvious, so hopefully these are okay.

Fixed by https://github.com/dungeons-of-moria/umoria/commit/d9e3fef954b54192388b907230dfcd6c0e3fcf7c
