### ISSUE TITLE
Turning on discussions?

### ISSUE THREAD

**Issue by Dr-WaSaBi** [dungeons-of-moria/umoria#38]
Any thoughts on turning on discussions for this repo?  Might be better then opening issues? 🤷🏽‍♂️

I was looking at the project tasks, and had some ideas on setting them up as milestones , and then breaking them down into issues and such.  

Just a thought.
Thanks, and have a great day.
Russ

**Comment by mrcook** [comment]
Hi Dr-WaSaBi, I don't think it's nescessary to enable discussions at the moment. If too many issues start being used for general discussion topics then it can be enabled easily enough.

When keeping in mind the goals of this 5.7 work, I'm not sure if there's too much to be discussed either. 


Milestones can be useful, but I think this can add a lot of administrative overhead which is maybe not useful for a project with such little activity. So far, the items in the project are also quite small and focused in their scope - well, except for breaking apart the UI/engine code (and there's plenty to do before that beast is tackled) - so I'm not sure these can be broken down too easily. Once these things become a pain point, it's easy to move to that workflow.

I've not been be so active this year - for the obvious reasons - but perhaps when the world get's back to normallity I'll be able to get back to working on this code.

**Comment by mrcook** [comment]
Hi Dr-WaSaBi, I don't think it's necessary to enable discussions - if too many issues start being used for general topics, it can be enabled easily enough.

Milestones can be useful, but I think this can also add a lot of administrative overhead, which is maybe not useful for such a low activity project like this. Items in the project are quite small and focused in their scope - well, except for breaking apart the UI/engine code (and there's plenty to do before that beast is tackled) - so I don't think these can be broken down easily. If this becomes a pain point it's easy to move to that work flow.

When keeping in mind the goals of this 5.7 work I'm not sure there's much to be discussed either. As the readme states: "_no intentional game play changes_", and I think this should also cover features such as adding colour, etc. Those items in the project cover the main topics that need doing before any kind of feature work is started, but if something important comes up, creating an issue is good enough for now.

I've not been be so active this year - for the obvious reasons - but perhaps when the world gets back to normal, I'll be able to get back to working on this code.
