### ISSUE TITLE
Invalid license - should be GPL-3.0-or-later

### ISSUE THREAD

**Issue by mrcook** [dungeons-of-moria/umoria#43]
In a careless change back when I first started this project I [inadvertently changed the license to GPL-2](https://github.com/dungeons-of-moria/umoria/commit/df109c5f55f6792dfd79055524728206f3a05247) from GPL-3.0-or-later.

This needs to be corrected by me.

cc/ @Eli-the-Bearded, @Grimler91, @russell-taylor, @sdicke, @steils

**Comment by Grimler91** [comment]
Licenses can be a bit confusing, are all the (old) files GPL-3.0-or-later? (Looks like it on [the commit that introduced the GPL](https://github.com/dungeons-of-moria/umoria/commit/24ef243f080522f6d832f862e2a05a879ea09994))

I am fine with licensing my minor contributions under GPL-3.0-or-later rather than GPL-2.0 (since I guess you would need to revert it otherwise? Again, licenses can be a bit confusing..)

**Comment by russell-taylor** [comment]
I'm fine with that change.

**Comment by mrcook** [comment]
All references to the old license have now been [replaced](https://github.com/dungeons-of-moria/umoria/commit/72bb92b907f6140302c8b1b5ae9a3ddb1085f8d5) and a [new version released](https://github.com/dungeons-of-moria/umoria/releases/tag/v5.7.15).
