### ISSUE TITLE
Disable Haggling option

### ISSUE THREAD

**Issue by acahir** [dungeons-of-moria/umoria#60]
In the manual, under options, there is an option to disable haggling:

> Disable haggling. This is off by default. When on, all haggling will be disabled at the cost of a 10 percent tax on the final price on items you would otherwise have had to haggle for, and all prices displayed in the stores will be the actual prices you have to pay.

This does not seem to be in the code currently, but you can see it was at some point. I had added this feature when I added color to 5.6, and again recently. Before submitting, is this a PR you are interested in?

**Comment by mrcook** [comment]
Hi Angus, one of the reasons I moved the manual to the historical directory was because it did not reflect what was happening in UMoria 5.6. In fact I don't think the manually had been updated for quite a long time even before that.

My goal was not to add additional game play features to the code, so I think it's best not to include the haggling option for now.

Thanks,
Michael.
