### ISSUE TITLE
better/classic wall characters?

### ISSUE THREAD

**Issue by dchmelik** [dungeons-of-moria/umoria#79]
Moria looked better in 1990s when I played it on DOS (than on UNIX/GNU/Linux) because used an extended ASCII block character for walls.  Some roguelikes revived this style with unicode.  Would it be possible to make this standard or option?  I know Moria also has a command to identify map character, and someone might type '#' but unless they want for some reason (and it says 'wall') I don't think that's necessary.  Hash/pound character just looks horrible for walls and feels harder to look at and play than when it had solid/connected walls.

**Comment by mrcook** [comment]
Hi @dchmelik, updating to something like this probably wouldn't be a huge task, making it optional would be a bit messier.

One of my original goals was to extract out rendering so that things like this could be supported (including colour and SDL support) but alas I no longer have that kind of time, so that's not now likely to happen.

If you we're thinking of making your own fork then perhaps [Umoria COLOR](https://github.com/andrewtweber/umoria-color) might be inspiration on where to start.
