### ISSUE TITLE
more mac installation issues

### ISSUE THREAD

**Issue by AtmPhys** [dungeons-of-moria/umoria#9]
Okay, now I have some new (different) issues. When I try to run the 'make packages' command, I now get this error:

> /Users/.../umoria-master/src/death.cpp:399:4: error: function declared
>       '[[noreturn]]' after its first declaration
> [[ noreturn ]] void exitGame() {
>    ^
> /Users/.../umoria-master/src/externs.h:166:6: note: declaration missing
>       '[[noreturn]]' attribute is here
> void exitGame();
>      ^

I tried modifying line 166 in externs.h to add the noreturn attribute in the function declaration (I've added in spaces before/after attribute to preserve underscores here, but they aren't in the code):

> void exitGame() __ attribute __((noreturn));

But I still got the same error; I'm not sure if I have the syntax wrong or there's something else I'm missing?

**Comment by mrcook** [comment]
On macOS they actually symlink clang to gcc, and it is that which is causing the problem.
I will have have to do some work to fix this but for the short term there are two options.

1. Install the latest GCC with Homebrew: `brew install gcc`. You will also need to manually symlink GCC: `ln -s /usr/local/bin/gcc-7 /usr/local/bin/gcc` and `ln -s /usr/local/bin/g++-7 /usr/local/bin/g++`.

2. If you're only interested in playing the game then perhaps download the binary from the releases: https://github.com/dungeons-of-moria/umoria/releases/tag/v5.7.4

Otherwise you will have to wait until I've pushed up the fix.

**Comment by mrcook** [comment]
Fixed by commit https://github.com/dungeons-of-moria/umoria/commit/ede8d0834aa016022c622a49de97c3036e322c2b
